from classes.Aggregation.aggregation_example import start_aggregation_example
from classes.Association.association_example import start_association_example
from classes.Composition.composition_example import start_composition_example

start_association_example()

start_composition_example()

start_aggregation_example()
